- name: Configuration et récupération de la configuration CSR1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: Récupère la configuration
      # On indique le nom du module
      cisco.ios.ios_command:
        name: GigabitEthernet1
        ipv4:
          - address: dhcp
            state: present
      register: result

    - name: Configurer l'interface GigabitEthernet2 avec IP 192.168.2.1/24
      cisco.ios.ios_l3_interface:
        name: GigabitEthernet2
        ipv4:
          - address: 192.168.2.1/24
        state: present

    - name: Configurer l'interface GigabitEthernet3 avec IP 192.168.3.1/24
      cisco.ios.ios_l3_interface:
        name: GigabitEthernet3
        ipv4:
          - address: 192.168.3.1/24
        state: present

    - name: Configurer l'interface GigabitEthernet4 avec IP 192.168.4.1/24
      cisco.ios.ios_l3_interface:
        name: GigabitEthernet4
        ipv4:
          - address: 192.168.4.1/24
        state: present